In [49]:
# add by qinglin, for jupyter notebook
%reload_ext autoreload
%autoreload 2

In [4]:
import numpy as np
import matplotlib.pyplot as plt
from asa.dataset import Dataset

# get data by name

In [5]:
x = np.random.normal(size=1000)
y = x**2 + np.random.normal(size=1000)
z = np.log(np.abs(x + y)) + np.random.normal(size=1000)

In [6]:
data = np.array([x, y, z]).T

In [7]:
dataset = Dataset(data, ['x', 'y', 'z'], ['x', 'y', 'z'])

In [8]:
np.array_equal(dataset['x'], x)

True

In [9]:
np.array_equal(dataset[['x', 'y']], np.array([x, y]).T)

True

You can also use index

In [10]:
np.array_equal(dataset[:, 0], x)

True

In [11]:
np.array_equal(dataset[3:5, 'x'], x[3:5])

True

# summary

In [12]:
x = np.random.normal(size=1000)
y = x**2 + np.random.normal(size=1000)
z = np.log(np.abs(x + y)) + np.random.normal(size=1000)

In [13]:
data = np.array([x, y, z]).T

In [14]:
dataset = Dataset(data, ['x', 'y', 'z'], ['x', 'y', 'z'])

In [15]:
dataset

Dataset summary:
  Data shape: (1000, 3)
  Names: ['x' 'y' 'z']
  Labels: ['x' 'y' 'z']

In [16]:
print(dataset)

Dataset summary:
  Data shape: (1000, 3)
  Names: ['x' 'y' 'z']
  Labels: ['x' 'y' 'z']



In [17]:
dataset.summary()

Dataset summary:
  Data shape: (1000, 3)
  Names: ['x' 'y' 'z']
  Labels: ['x' 'y' 'z']



## add col

In [18]:
x = np.random.normal(size=1000)
y = x**2 + np.random.normal(size=1000)
z = np.log(np.abs(x + y)) + np.random.normal(size=1000)

In [19]:
data = np.array([x, y, z]).T

In [20]:
dataset = Dataset(data, ['x', 'y', 'z'], ['x', 'y', 'z'])

In [21]:
x2 = np.random.normal(size=1000)
y2 = 5 * x2

data2 = np.array([x2, y2]).T

In [22]:
dataset.data

array([[ 1.67597404,  2.24969179,  2.00278094],
       [ 1.12975521,  1.41880734,  1.330204  ],
       [-0.17336716,  1.79213939,  0.07338984],
       ...,
       [-0.18998541,  0.32944409, -1.00180711],
       [ 1.36732326,  1.704963  ,  0.26352576],
       [ 0.04585722,  0.81908627, -0.56355543]])

In [23]:
dataset.add_col(data2, ['x2', 'y2'], ['x2', 'y2'])

In [24]:
dataset.data

array([[ 1.67597404,  2.24969179,  2.00278094,  0.14838732,  0.74193659],
       [ 1.12975521,  1.41880734,  1.330204  ,  0.59128865,  2.95644323],
       [-0.17336716,  1.79213939,  0.07338984, -0.93853786, -4.69268928],
       ...,
       [-0.18998541,  0.32944409, -1.00180711, -0.19226154, -0.96130772],
       [ 1.36732326,  1.704963  ,  0.26352576,  1.00945481,  5.04727403],
       [ 0.04585722,  0.81908627, -0.56355543,  0.85782916,  4.28914578]])

In [25]:
dataset.labels

array(['x', 'y', 'z', 'x2', 'y2'], dtype='<U2')

In [26]:
dataset.names

array(['x', 'y', 'z', 'x2', 'y2'], dtype='<U2')

In [27]:
dataset.add_col(x2, 'x3', 'x3')

In [28]:
dataset.data

array([[ 1.67597404,  2.24969179,  2.00278094,  0.14838732,  0.74193659,
         0.14838732],
       [ 1.12975521,  1.41880734,  1.330204  ,  0.59128865,  2.95644323,
         0.59128865],
       [-0.17336716,  1.79213939,  0.07338984, -0.93853786, -4.69268928,
        -0.93853786],
       ...,
       [-0.18998541,  0.32944409, -1.00180711, -0.19226154, -0.96130772,
        -0.19226154],
       [ 1.36732326,  1.704963  ,  0.26352576,  1.00945481,  5.04727403,
         1.00945481],
       [ 0.04585722,  0.81908627, -0.56355543,  0.85782916,  4.28914578,
         0.85782916]])

In [29]:
dataset.names

array(['x', 'y', 'z', 'x2', 'y2', 'x3'], dtype='<U2')

## add row

In [30]:
x = np.random.normal(size=2)
y = x**2 + np.random.normal(size=2)
z = np.log(np.abs(x + y)) + np.random.normal(size=2)

data = np.array([x, y, z]).T

In [31]:
dataset = Dataset(data, ['x', 'y', 'z'], ['x', 'y', 'z'])

In [32]:
dataset.data

array([[ 1.06480947,  1.86882949, -0.04833452],
       [-0.2536447 , -0.65262798,  0.28142592]])

In [33]:
dataset.add_row(data)

In [34]:
dataset.data

array([[ 1.06480947,  1.86882949, -0.04833452],
       [-0.2536447 , -0.65262798,  0.28142592],
       [ 1.06480947,  1.86882949, -0.04833452],
       [-0.2536447 , -0.65262798,  0.28142592]])

## delete col

In [50]:
x = np.random.normal(size=2)
y = x**2 + np.random.normal(size=2)
z = np.log(np.abs(x + y)) + np.random.normal(size=2)

data = np.array([x, y, z]).T

In [51]:
dataset = Dataset(data, ['x', 'y', 'z'], ['x', 'y', 'z'])

In [52]:
dataset.data

array([[ 0.44195621,  1.41335667,  0.91624984],
       [-0.01707149,  1.20553685,  0.89957627]])

In [53]:
dataset.del_col(1)

In [54]:
dataset.data

array([[ 0.44195621,  0.91624984],
       [-0.01707149,  0.89957627]])

In [55]:
dataset.summary()

Dataset summary:
  Data shape: (2, 2)
  Names: ['x' 'z']
  Labels: ['x' 'z']



In [56]:
dataset.del_col('x')

In [57]:
dataset.data

array([[0.91624984],
       [0.89957627]])

In [58]:
dataset.summary()

Dataset summary:
  Data shape: (2, 1)
  Names: ['z']
  Labels: ['z']



## delete row

In [36]:
x = np.random.normal(size=2)
y = x**2 + np.random.normal(size=2)
z = np.log(np.abs(x + y)) + np.random.normal(size=2)

data = np.array([x, y, z]).T

In [37]:
dataset = Dataset(data, ['x', 'y', 'z'], ['x', 'y', 'z'])

In [38]:
dataset.data

array([[-1.07477946,  1.27267112, -1.42611577],
       [ 0.39861649, -1.77036889, -0.05582315]])

In [41]:
dataset.del_row(1)

In [42]:
dataset.data

array([[-1.07477946,  1.27267112, -1.42611577]])